### ISSUE TITLE
Character Reference Support in useapi

### ISSUE THREAD

**Issue by vranky** [useapi/midjourney-api-client#1]
It could be possible to extend useapi with recently added Character Reference feature from midjourney?

**Comment by useapi** [comment]
We fully support all Midjourney features including `--cref`.
Try this prompt
`A man is celebrating the victory of the revolution on the barricades in Paris with his fist in the air --cref https://runtheprompts.com/wp-content/uploads/2024/03/dick-smith-base-image.jpg --cw 80 --v 6.0`
Example image taken from this [article](https://runtheprompts.com/resources/midjourney-info/consistent-characters-solved-cref-parameter/)

**Comment by vranky** [comment]
goot thx!
